### ISSUE TITLE
-a

### ISSUE THREAD

**Issue by Pussydestroyer69DK** [TAAPArthur/CrunchyrollGuestPassFinder#3]
I have no idea how to use the -a command. I have written every account down on the accounts.json file. 
![image](https://user-images.githubusercontent.com/72362094/95028575-4b6f0380-06a1-11eb-819c-387a62e59beb.png)
![Unavngivet](https://user-images.githubusercontent.com/72362094/95028616-9c7ef780-06a1-11eb-8be2-5efe04fa5e17.png)

**Comment by TAAPArthur** [comment]
So in general I would avoid the screenshots and rely on a textual representation of the problem and the the output of the command, description of what the expected and actual behavior was and an accurate title. For an example of the output of the command:
```
$ crunchyroll-guest-pass-finder.py -a
usage: crunchyroll-guest-pass-finder.py [-h] [--auto AUTO] [--delay DELAY] [--log-level {CRITICAL,ERROR,WARNING,INFO,DEBUG,NOTSET}] [--dry-run]
                                        [--username USERNAME] [--password PASSWORD] [--save] [--list-users] [-v]
crunchyroll-guest-pass-finder.py: error: argument --auto/-a: expected one argument
```

That said this is a simple problem. The auto option was expecting an explicit argument. 
`crunchyroll-guest-pass-finder.py -a true` would work. I agree with you though that this isn't intuitive and wasn't intentional. 

Thanks for pointing it out and it'll be fixed shortly

**Comment by Pussydestroyer69DK** [comment]
> So in general I would avoid the screenshots and rely on a textual representation of the problem and the the output of the command, description of what the expected and actual behavior was and an accurate title. For an example of the output of the command:
> 
> ```
> $ crunchyroll-guest-pass-finder.py -a
> usage: crunchyroll-guest-pass-finder.py [-h] [--auto AUTO] [--delay DELAY] [--log-level {CRITICAL,ERROR,WARNING,INFO,DEBUG,NOTSET}] [--dry-run]
>                                         [--username USERNAME] [--password PASSWORD] [--save] [--list-users] [-v]
> crunchyroll-guest-pass-finder.py: error: argument --auto/-a: expected one argument
> ```
> 
> That said this is a simple problem. The auto option was expecting an explicit argument.
> `crunchyroll-guest-pass-finder.py -a true` would work. I agree with you though that this isn't intuitive and wasn't intentional.
> 
> Thanks for pointing it out and it'll be fixed shortly

It only logins to 1 account:

> C:\Users\itzro>python "C:\Users\itzro\Desktop\CrunchyrollGuestPassFinder-master (3)\CrunchyrollGuestPassFinder-master\crunchyroll-guest-pass-finder.py" -a true
> INFO:logged into itzrondy
> INFO:searching for guest passes
> INFO:Assuming [] are already used
> INFO:Trial 

> 0

>

**Comment by TAAPArthur** [comment]
It'll login into 1 account at a time. It basically loops over all accounts and does the scraping for each one. If the script tried to do run each  in parallel, they'd just compete with each other and the process wouldn't go any faster.
